<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>NavisClashOrder</AssemblyName>
    <RootNamespace>Redomine.NavisClashOrder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Navisworks.Api">
      <HintPath>C:\Program Files\Autodesk\Navisworks Manage 2024\Autodesk.Navisworks.Api.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Autodesk.Navisworks.Clash">
      <HintPath>C:\Program Files\Autodesk\Navisworks Manage 2024\Autodesk.Navisworks.Clash.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Clash Detective.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
